/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libraw_javax_imageio_LibRawImageReader */

#ifndef _Included_org_libraw_javax_imageio_LibRawImageReader
#define _Included_org_libraw_javax_imageio_LibRawImageReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libraw_javax_imageio_LibRawImageReader
 * Method:    loadImageFromFilePath
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_libraw_javax_imageio_LibRawImageReader_loadImageFromFilePath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_libraw_javax_imageio_LibRawImageReader
 * Method:    loadImageFromImageInputStream
 * Signature: (Ljavax/imageio/stream/ImageInputStream;)I
 */
JNIEXPORT jint JNICALL Java_org_libraw_javax_imageio_LibRawImageReader_loadImageFromImageInputStream
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
